### PR TITLE
first draft to use the joomla core module techniques

### PR DESCRIPTION
**Pull request by reilldesign**
To be able to select mod_jem overrides  (layouts) via dropdown.

### CODE REVIEW

**Comment by mckillo** [comment]
In the lastest version 4.2.3 (dev in github):
- The calendar icons (navigation controls) were changed to Font Awesome icons.
- The issue with the masked icon couldn't be reproduced, and this commit adds a unnecessary line (space on top).
- A draft to improve the layout in modules could be addressed by module override, 

On the last point, there is a lot of code improvement in JEM, so this should be kept in mind for future versions and JEM should be updated to support the Joomla 6 core and to facilitate the creation of new layouts in JEM (low priority).

**Comment by reilldesign** [comment]
An override is indeed possible. But how can I create different overrides if I can't choose the layout?

**Comment by mckillo** [comment]
I agree. If you need more layouts, an override will be a solution if you want to modify one of them (default, responsive).

Please provide a description of a real case and an example of a layout, so we can evaluate it. Thank you for your expertise and ideas to improve JEM.

The layout is defined as a global setting, and the component and modules display the style based on this setting. Currently, JEM has two layouts and could potentially have more, but adding them would require further code changes.

I have tested the necessary changes and can create new layouts for the JEM modules, but I still need to finish testing.

**Comment by reilldesign** [comment]
Joomla Overrides are a very powerful way to change design and functions. I currently use a mod_jem override to pass event dates to a form (booking). For me it is not important that there are different layouts in the core, but that I can make full use of the override possibilities that the Joomla core provides. The core should only have a clean responsive layout to simplify maintenance.

**Comment by mckillo** [comment]
image

Tested and it works.

If the JEM module uses the layout module, then the JEM module is independent of the Global Layout settings. Each module can have a different layout in its advanced module settings.

Should we change all JEM modules to use the layout settings in the module?
This way, the admin has more flexibility to choose the module's layout, including making it easier to create a new layout.

**Comment by mckillo** [comment]
@jojo12 Have you seen the proposed changes for the module? When you have time.

**Comment by jojo12** [comment]
I don't understand this issue.

**Comment by mckillo** [comment]
This is a PR to utilize the Joomla Layout (overrides) in modules. 

JEM currently has only two layouts defined in the code: Responsive (in the responsive folder) and Legacy (default).
When you publish a module, all JEM modules use either the responsive or default layout, which is defined in the JEM settings (static).
If JEM has a global setting with 'responsive,' you can't use the default layout (style) in the new JEM basic module.

With the improvements from this PR, administrators gain three benefits:

1. We can use either the responsive or default layout (by default, it will match the JEM setting).
2. We can create new layouts for each JEM module by simply copying the PHP file of one of the existing layouts.
3. We can create a new CSS file for each layout.

This is an example for the basic JEM module, but it can be extended to other JEM modules. I create a new layouts to ilustrate this case. The JEM Basic module is one, but this module has 5 layouts (responsive, legacy and 3 news).

**Comment by mckillo** [comment]
This PR is closed, but there is a issue with change of model to use Joomla layout in the JEM module.

The development for this can be seen in the layout-modules branch and will be included in JEM 4.4.0 once the model is completed for all modules.

@reilldesign, thank you for the idea and contribution; with it, JEM will be better and more flexible in an upcoming version.

More information and tracking of the changes: https://github.com/jemproject/JEM-Project/issues/1803

**Pull request closed without merging**
