### PR TITLE
Add "Unpublish old events" to "Handle Old Events" settings

### PR DESCRIPTION
**Pull request by sternenvogel**
Add "Unpublish old events" to "Handle Old Events" settings 

according to @hekla on https://www.joomlaeventmanager.net/forum/jem-2-2-x-on-joomla-3/10298-setting-handle-old-evens (plus some fix)

Feature request: See https://www.joomlaeventmanager.net/forum/feature-requests/11212-handle-old-events-settings-add-unpublish-old-events-option

Currently only published events can be unpublished or trashed. I think this could also be done for events with status "archived"?

### CODE REVIEW

**Comment by luzernervogel** [comment]
Currently only published events can be unpublished or trashed. I think this could also be done for events with status "archived"?

**Comment by jojo12** [comment]
Thanks, I am trying.

**Comment by sternenvogel** [comment]
Just added the suggestion for a expiration meta tag, if old events will be archived or removed.

**Comment by sternenvogel** [comment]
PS: Do I need to add any translation files (e.g. DE) for the new option? Or will you do that?

**Comment by jojo12** [comment]
@sternenvogel: No, after updating, the english expression will be added to transifex, then we /I will translate and after the new translation will be added. (Perhaps there would be an easier way, but until now it was like that!

**Comment by jojo12** [comment]
I agree to add an expiration metatag!

**Comment by jojo12** [comment]
@sternenvogel:
the expiration metatag should be added in views/tmpl/responsive/default.php too!

**Comment by sternenvogel** [comment]
Done :) Thanks for the hint.

**Comment by sternenvogel** [comment]
Cool, thanks a lot @jojo12 - Do you already have an idea when you will publish the next release? 

Btw. in the change log, I think a release date would be great for each release. 
https://www.joomlaeventmanager.net/project/changelog-jem-2
Same in the download archive. 
https://www.joomlaeventmanager.net/download-archive

Thanks for your work!!

**Pull request merged**
