### PR TITLE
masked icon buttons

### PR DESCRIPTION
**Pull request by reilldesign**
in layout com_jem view-event

the icon buttons (.buttons) are not clickable and masked by h1.componentheading

### CODE REVIEW

**Comment by jojo12** [comment]
Sorry, I can't reproduce your issue: in Frontend event details, I can click every button in cassiopeia as in t4_purity.

**Comment by reilldesign** [comment]
@jojo12 you are right. This happens because I set h1, h2, h3 { position: relative; } to style them.

**Comment by Heklaterriol** [comment]
I haven't found yet, where this occurs. Could you please provide a screenshot.

**Comment by reilldesign** [comment]
Bildschirmfoto 2024-08-08 um 16 23 03

site com_jem wrapper-static view-event

**Comment by Heklaterriol** [comment]
I cannot reproduce it, not with `h1, h2, h3 { position: relative; }` (or maybe I just don't get it ;-), but as `float` anyway might have unwanted/unexpected side effects on neighbour elements I would also prefer `text-align`.
@jojo12 If you have checked it and think it is ok, we can take it.

**Review by Heklaterriol — APPROVED** [review]

**Comment by mckillo** [comment]
I cannot reproduce this issue with casiopeia template. All icons are clickable and work.

**Pull request closed without merging**
