### PR TITLE
Enhance CSV Import / Export, make configurable, add same behavior to all functions

### PR DESCRIPTION
**Pull request by mwelters**

### CODE REVIEW

**Comment by mwelters** [comment]
I am disencouraged that nobody reviews my Merge Request after more than a month...

**Comment by Egnarts94** [comment]
Hey @mwelters could you please create a new pull-request with those changes to https://github.com/Egnarts94/JEM-Project/tree/develop-egnarts I will test your changes and include them into the big pull-request

**Comment by JKoelman** [comment]
@mwelters first of all thx for changes and effort that comes with it.    

I also do understand what you mean.  Not sure what the problem is why nobody reviewed it in all those months....  Basicly it's up to @Hoffi1  (and others) to take a look at the changes, respond and decide if it can be added. Luckily @Egnarts94 did respond to you.

can say that after having a long long break i've decided to be a bit more active with the project again as it's a bit of a standstill at the moment.  For now I'll help out with support (JEM2 and JEM3),  but the dev part for JEM2.x is for others.

**Comment by depebo** [comment]
@mwelters @JKoelman This has been merged (with thanks!) into @Egnarts94 responsive and will come here as a part of responsive pull shortly.

**Pull request closed without merging**
