### PR TITLE
Jem 4.2.3 dev

### PR DESCRIPTION
**Pull request by Pinkeltje**
Remove language files from plugin and move them to administrator/language. Added some lines in language file to be able to use language overrides. Needs additions on Transifex as well.

### CODE REVIEW

**Comment by Heklaterriol** [comment]
I did not understand your added language strings, since they are not used in the code.
What are your ideas with them?

**Comment by Pinkeltje** [comment]
When trying to find language constant to make an override for Dutch language and setting language debug to constant I discovered that Event didn't have a language constant.
Schermafbeelding 2024-10-15 105405After adding constants to language file constant was shown so that I could make an override for it.
Schermafbeelding 2024-10-15 103332
Must be called by a script or something in general finder plugin or component because searching for i.e.
`PLG_FINDER_QUERY_FILTER_BRANCH_P_EVENT` in entire site doesn't show anything.

**Comment by jojo12** [comment]
I find the following warnings:  (index> filter options:)
**Warning: Undefined array key 4 in C:\xampp\htdocs\joomla\administrator\components\com_finder\src\Field\ContentmapField.php on line 109

Warning: foreach() argument must be of type array|object, null given in C:\xampp\htdocs\joomla\administrator\components\com_finder\src\Field\ContentmapField.php on line 109

Warning: Undefined array key 6 in C:\xampp\htdocs\joomla\administrator\components\com_finder\src\Field\ContentmapField.php on line 109

Warning: foreach() argument must be of type array|object, null given in C:\xampp\htdocs\joomla\administrator\components\com_finder\src\Field\ContentmapField.php on line 109

Warning: Undefined array key 8 in C:\xampp\htdocs\joomla\administrator\components\com_finder\src\Field\ContentmapField.php on line 109

Warning: foreach() argument must be of type array|object, null given in C:\xampp\htdocs\joomla\administrator\components\com_finder\src\Field\ContentmapField.php on line 109

Warning: Undefined array key 2 in C:\xampp\htdocs\joomla\administrator\components\com_finder\src\Field\ContentmapField.php on line 109

Warning: foreach() argument must be of type array|object, null given in C:\xampp\htdocs\joomla\administrator\components\com_finder\src\Field\ContentmapField.php on line 109**

**Comment by Pinkeltje** [comment]
Unable to reproduce
2024-10-15 Screenshot 648

**Comment by Pinkeltje** [comment]
@Heklaterriol : see also plg_finder_content.ini
`PLG_FINDER_QUERY_FILTER_BRANCH_P_ARTICLE="Articles"
PLG_FINDER_QUERY_FILTER_BRANCH_P_AUTHOR="Authors"
PLG_FINDER_QUERY_FILTER_BRANCH_S_ARTICLE="Article"
PLG_FINDER_QUERY_FILTER_BRANCH_S_AUTHOR="Author"`

**Comment by jojo12** [comment]
I think, we have to learn much more about the smart search. But with this plugin, we and friends can work! Let's go!

**Comment by Pinkeltje** [comment]
Maybe change this in sys.ini
PLG_FINDER_JEM = "JEM - Smart Search Plugin"
To
PLG_FINDER_JEM = " Smart Search - JEM"
Small detail but name  then is the same structure as core finder plugins.

**Comment by Heklaterriol** [comment]
> PLG_FINDER_JEM = " Smart Search - JEM"

Yes, I thought about this too.

**Pull request merged**
