### PR TITLE
Implement JEM-Responsive to JEM

### PR DESCRIPTION
**Pull request by Egnarts94**
This version includes JEM-Responsive to JEM and fixes some bugs.
Changelog:
* Add Backend->Jem->Settings->Basic Settings a new entry called "Style". This are the global settings for enabling JEM-Responsive
* Add JEM-Responsive Layout to all component views and most modules
* Add FontAwesome now also available in the default JEM views (FA-Icons has class to style them using custom css)
* Add Backend-Documentation for JEM-Responsive
* Add option to show only featured events in eventlist view
* Add Hotfix for SqueezeBox for better style on mobile phones
* Add Backend setting to show not only attending users in event view. With this setting enabled, attending, waiting list, invited and not attending users are shown in the event view
* Change models/event.php now requests comment from database to show later in a template override in the event view
* Fix PHP warning in some view.html files: public function display() -> public function display($tpl = null)
* Fix plg_content_jemlistevents were not built
* JEM-Responsive supports now the backend-css settings of JEM->Settings->Layout
* Fix deprecated php-function create_function()
* Fix https://github.com/Egnarts94/JEM-Project/commit/d79575867fdb63ec49784ea65155f080a213099d
* Includes commit https://github.com/jemproject/JEM-Project/commit/c82469cdad1b934e8ad61688674b1d3d374c8363

Tested with Joomla 3 and 2.5. All Tests were successful.

Test-Build (Updated 26.01.19 14:16):
[pkg_jem_v2.3.0-dev2.0.zip](https://github.com/jemproject/JEM-Project/files/2799003/pkg_jem_v2.3.0-dev2.0.zip)

### CODE REVIEW

**Comment by Kralyk** [comment]
Hello,
I have a suggestion for one improvement:

Displaying user comments in view event (which users write during registration) in a listing of all attended and unattended people?

Would it be set up within these adjustments?

Optionally even with the ability to enable or disable this view (eg only for guest, registered, etc.) in the JEM administration.

I think it would be a great improvement.

Thank you and kind regards.

**Comment by jojo12** [comment]
I am **agains**t the proposal of kralyk because of safety (abuse) and privacy! The eventmakers can see (and even print/export the list the comments included in the attendingmanager. This works just in actual JEM. 
(You must be logged in in FE as admin and must attend the event, then you can click on the number of attendees and can reach like that the attending manager). I personally added an icon "external_link" to this number.)
At least we have to discuss this proposal!

**Comment by Egnarts94** [comment]
Sorry, I did not understand Kralyks change-request. But @Kralyk please open a new issue if you want to have something changed. This Pull-Request is just to discuss about merching my update into the original JEM.

**Comment by Kralyk** [comment]
I'm sorry, I've seen here that settings for attended and unattended viewing will be. So please put it in the right place, I do not know much about github.

My opinion: In my case, these comments are information for other users as well, for example
- that someone will come to the event later
- He takes another person
- why not come, etc.

Personally, with JEM, I organize a meeting of our sports section in the gym, weekend trips, etc. - so I consider this information important also for other JEM users.

So, in my case, it's not private information, so I need this information to display in the frontend best right in view event.

And if someone considers it private information then it would be possible to view only for registered, admin or guest, etc.

**Comment by jojo12** [comment]
[I made a new issue with the other theme!]

**Comment by jojo12** [comment]
pkg_jem_v2.3.0-dev1.19.zip: well done, thanks!

**Comment by Kralyk** [comment]
Hello,
I went into testing this version and I probably found one mistake.

The created event does not show the venue, even if it is specified. Only the heading for venue will be displayed. Once you click on editing the venue there is entered, but it is not visible in the event.

At the same time, the venue is displayed at the top.

If I turn on "Address Display" in the setting, the address and map will be displayed as well.

If I switch to the default table style, it will show a link to the event location - which I think is correct, but there is a bit more extra because the link is already up.
  

I hope I understand it clearly, my English is not very good.

Thanks for your work.

image

**Comment by Egnarts94** [comment]
Thanks, that is a bug, you are right.
I created an issue: https://github.com/Egnarts94/JEM-Project/issues/17

**Comment by jojo12** [comment]
I tested pkg_jem_v2.3.0-dev1.19.zip and exchanged the later changed files (until Issue #20)
It works fine!

**Comment by Egnarts94** [comment]
Close because it is outdated branch.

**Pull request closed without merging**
