### PR TITLE
Update helper.php

### PR DESCRIPTION
**Pull request by knackko**
Added country to display in module. Can show a country flag in the module based on country code.
Example in sidebar: http://www.old-drivers-spirit.fr/grand-prix-series

### CODE REVIEW

**Comment by jojo12** [comment]
for the discussion: I am not sure, if this is needed for module. The modules should lead to the event details. Not too much in the modules.

**Comment by Heklaterriol** [comment]
Would be nice, to have the possibiliy to display countries in modules – makes it more flexible for a large spectrum of usage

**Comment by Heklaterriol** [comment]
The is is obsolete/outdated now, isn't it?

**Comment by mckillo** [comment]
In Joomla has \media\mod_languages\images all flag icons, we can use these native icons in JL, but the resolution is very low (18x12).
I found info about it in https://issues.joomla.org/tracker/joomla-cms/35554 (proposal to update flag icons in JL4 - Denied)

Here is the package, but add 2MB to JEM (alot of):
https://flagicons.lipis.dev/
https://github.com/lipis/flag-icon-css/blob/master/LICENSE MIT license

I think that JEM could have an option to show the native icons to show the country of event in the JEM modules.

**Comment by mckillo** [comment]
JEM4-add-country_flag-module_for_each_event

what is your opinion?

**Comment by jojo12** [comment]
For me its too much, and when I have only events in Switzerland, then it looks very nacionalistic!

**Comment by mckillo** [comment]
You can select 'Np' (by default)

**Comment by jojo12** [comment]
Ok?

**Comment by Heklaterriol** [comment]
For me it is OK, if I can turn it off and if it is off by default.

**Comment by mckillo** [comment]
Yes, this is the config, Off by default and change option in each module.
See commit above.
I think that in the near future, JL4 or JL5 should improve the quality icon as link of forum Joomla (SVG would be perfect).
Thanks and closed (one less).

**Comment by Heklaterriol** [comment]
> Yes, this is the config, Off by default and change option in each module.

Yes, lets include it and it ist the admins choice then to do waht he/she wants …

**Comment by Heklaterriol** [comment]
> I think that in the near future, JL4 or JL5 should improve the quality icon as link of forum Joomla (SVG would be perfect).

Maybe it is possible to include externaly loaded flags, so we do not have to include it in the packege … I check it.

**Comment by Heklaterriol** [comment]
svg would be nice, **but** I came to the opinion that I find webp files more useful, because:
- we do not need the flags scalable and rich in detials as svg provides
- complicated/detailed flags have large file sizes in svg (like el salvador: 242 kb)
- in webp 254 flags in the size 180 x 120 Pixel are ca 260kb in size (all together), the larget flag is 7kb.

Source of webp flags for this: https://flagpedia.net/download/icons

Would also be possible to embed them via CDN
```
<picture>
  <source
    type="image/webp"
    srcset="https://flagcdn.com/h60/za.webp,
      https://flagcdn.com/h120/za.webp 2x">
  <source
    type="image/png"
    srcset="https://flagcdn.com/h60/za.png,
      https://flagcdn.com/h120/za.png 2x">
  <img
    src="https://flagcdn.com/h60/za.png"
    height="60"
    alt="South Africa">
</picture>
```
For other flags just replace za with other [ISO 3166 country codes](https://flagcdn.com/en/codes.json)

What do you think?

**Comment by Heklaterriol** [comment]
… and if Joomla updates its flag some day, we can then use them.

**Comment by mckillo** [comment]
That resolution of 180 x 120 Pixel is good/perfect, It's enought  it's x10 of native icons in Joomla.

**Comment by mckillo** [comment]
I think that this feature can be dinamic, the admin can load other more folder with other format and resoluction, and select by JEM setting 

JEM4-load_dinamic_folder_flag_icon-selected_by_setting

For example, JEM has a folder for flag icons in media/flags. If we move those files to folder w16-gif and add a new folder with the flag files that you have referenced, we have w160-webp. And other for w250-png (other package).

The name of folder is important (w250-png is width 250px in png format), and this info show in the select field (JEM Setting).

What do your opinion about this? Do you like? @jojo12  @Heklaterriol

**Comment by mckillo** [comment]
Even the w16-gif folder is a copy of the Joomla one, we can delete it and use the native icons of Joomla from  \media\mod_languages\images

**Comment by Heklaterriol** [comment]
> I think that this feature can be dinamic, the admin can load other more folder with other format and resoluction, and select by JEM setting

Yes, would be nice, if you want to implement it.

**Comment by Heklaterriol** [comment]
and at the moment we use two flag sources:
- in the JEM Basic module: media/mod_languages/images/en.gif
- in the JEM component: media/com_jem/images/flags/en.gif

Should be the same at the end.

**Comment by Heklaterriol** [comment]
I added a check it the country is set, because otherwise we get a "0" and with that a broken image instead of a country code 
[check if coutnry is set for flag](https://github.com/jemproject/JEM-Project/commit/c9187b83220f410e64998ab1570cddff4762103b)

**Comment by mckillo** [comment]
I was mistaken, media/mod_languages/images/ folder is flag for languages, not country. for this reason, JEM has its own folder for country icon. Change to media/com_jem/images/flags/w16-gif/ folder

**Comment by mckillo** [comment]
I 'm going to add new folder with an update of flag icon --> original version of 20x px from https://flagpedia.net/download/icons

**Comment by mckillo** [comment]
What do we do with the old icons? Delete or move to new w16-gif folder?

**Comment by mckillo** [comment]
JEM4-folder_for_set_flag_icon-selected_by_setting

It is understood?

**Comment by mckillo** [comment]
I think with this feature is finished and PR can be closed.

**Comment by Heklaterriol** [comment]
What is your idea with letting the user choose the path to the images?
Why not define it and have the flag files in de defined place?

**Comment by mckillo** [comment]
The admin can choose other flag imagen set in other folder (without overwritting files), with other style, resolution and extension.

**Comment by jojo12** [comment]
Would be good to have the standard as fallback

**Comment by mckillo** [comment]
I think that the standar could be this new w20-png directory (by default) and save old set in w16-gif (admin doesn't want to change flag icon set). For it I asked: 'What do we do with the old icons? Delete or move to new w16-gif folder?'

Other option, it's update flag icon set and delete path in the setting, if the user want to change the icons, you just have to overwrite them.

**Comment by mckillo** [comment]
What do we do with the old icons? delete them?

**Comment by Heklaterriol** [comment]
> What do we do with the old icons? delete them?

Anything that speaks against it? Or leave them and mark them for being deleted later?

**Comment by mckillo** [comment]
What is the final decision? The old files aren't used in JEM 4. 
How does it close this PR? Move to folder or delete? 
The news flags icon are a little better. My vote is to delete them and request of PR is implemented, PR closed.

**Comment by jojo12** [comment]
I would say yes

**Comment by mckillo** [comment]
Other style or places?

**Comment by mckillo** [comment]
Done. this PR can be closed.

**Pull request closed without merging**
