### PR TITLE
Event registration hours

### PR DESCRIPTION
**Pull request by jojo12**
Tested this new feature, ok

### CODE REVIEW

**Comment by Heklaterriol** [comment]
When updateing 4.3.0 with the actual state of the branch JEM-4.3.1-dev I get an error:
`JInstaller: :Install: Error SQL Incorrect datetime value: '1' for column `dbname1`.`j5px_jem_events`.`unregistra_until` at row 6`

**Comment by Heklaterriol** [comment]
Also when clean installing the actual state of the branch JEM-4.3.1-dev I cannot create an event:
`Save failed with the following error: Data too long for column 'registra_from' at row 1`

**Comment by mckillo** [comment]
You hace un the script 4.3.1.sql. Hijo had the dame issue (see below)

**Comment by mckillo** [comment]
@Heklaterriol, please check this last commit. The correct type for these fields is DATETIME. In this commit, the sample data, the installation SQL file, and update_4.3.1.sql have been updated. In update_4.3.1.sql, I have added the conversion of the unregistra_until field from hours to DATETIME. This last change is intended for verification within a JEM installation package.

**Pull request merged**
